### PR TITLE
Update main nav menu

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by psndcsrv** [comment]
I don't think we assign roles other than `member` to teachers when they sign up. Elsewhere in the portal, we use `if current_visitor.portal_teacher` to check if the current user is a teacher. Other than that, the changes look ok.

**Comment by dougmartin** [comment]
Ok - I changed the check current_visitor.portal_teacher.

**Comment by dougmartin** [comment]
The Travis failure doesn't seem related to these changes.

**Comment by psndcsrv** [comment]
I agree, it looks unrelated. The changes look good, so I'll merge it.

**Pull request merged**
