### PR TITLE
remove time estimate tag on portal listings

### PR DESCRIPTION
**Pull request by ddamelin**

### CODE REVIEW

**Comment by dougmartin** [comment]
@ddamelin You also need to run the build step manually and checkin the build results with the PR.  To do that:

1. Change into the `react-components` folder
2. Install the dependencies using `npm ci` (note: use node 12 as the `package-lock.json` file is in the old format)
3. Run `npm build` which will create a built Javascript file
4. Commit the built file.

**Comment by ddamelin** [comment]
build commited.

**Review by dougmartin — APPROVED** [review]
Looks good :+1:

**Review by scytacki — CHANGES_REQUESTED** [review]
@ddamelin can you run this by Cynthia and Kiley? 

They would know if it is OK or not.

**Comment by ddamelin** [comment]
@scytacki Kiley already suggested in Slack that it didn't make sense to show these numbers. She also suggested I make a story about it and that she would see about scheduling it. Given how simple it was to address, I submitted the PR instead.

**Comment by scytacki** [comment]
OK so then you just need to check with Cynthia. I believe she was a designer of these original numbers. She might want the replaced with something more generic.

**Comment by ddamelin** [comment]
OK

**Comment by ddamelin** [comment]
@scytacki @dougmartin Cynthia is on board with removing the times. I pushed a few more commits to address the fact that we could sort by time, so that is now removed as well.

**Review by dougmartin — APPROVED** [review]
Looks good :+1:

**Review by scytacki — APPROVED** [review]
Looks good to me

**Comment by dougmartin** [comment]
@ddamelin We need to wait until master is tagged with the `2.5.4` release is tagged to merge this PR.

**Pull request merged**
