### PR TITLE
Fix CI test failures caused by ChromeDriver (PT-185924955)

### PR DESCRIPTION
**Pull request by 433eros**
See story card PT-185924955 for more information

### CODE REVIEW

**Review by scytacki — CHANGES_REQUESTED** [review]
Did you try the more forward compatible solution described here:
https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1641879165

Basically remove webdrivers and upgrade selenium-webdriver. It sounds like it has to be version 4.11.0 for this approach to work.

**Comment by dougmartin** [comment]
@scytacki @433eros sure - I'll try to fix it locally on my dev box and then update this PR with any working changes.

**Comment by dougmartin** [comment]
@scytacki @433eros I tried updating the capybara gems here (https://github.com/concord-consortium/rigse/pull/1209/commits/df8aa5eeb88b90b9354ac8341eba836dd9068fc5) and we are still getting the same error.

I don't have time this week to dive into dependency hell - I suggest we add this to the T1 Tech Debt list and revert the last two commits to get back to a green build for now.

**Review by scytacki — APPROVED** [review]
Sounds good to me.

**Pull request merged**
