### PR TITLE
Add create collabspace activity in authoring page

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by scytacki** [comment]
The code for the publish api is here: https://github.com/concord-consortium/rigse/blob/master/app/controllers/external_activities_controller.rb#L246
This feature test documents most of the features of the publish api:
https://github.com/concord-consortium/rigse/blob/master/features/activity_runtime_api/publish.feature#L1

The 3 problems I can see with using the existing publish api are:
- it might assume you are going to include some sequence and activity structure. I expect that would be easy to change, so this structure can be optional.
- it might assume the launch_url is set, which you probably don't want to set. Setting this will make the portal think this activity has a portal report. So making that optional as well is important.
- it might not have support for the `append_auth_token` flag which you need. That should be easy to add.

**Comment by scytacki** [comment]
Looking at it more. I'm going to retract this approach. Adding a new api like you did is fine, but it should not be specific to collabspace. It should just be an json way to fill out the external activity form. The external_report_id can be handled the same way as the publish api. Where a URL is passed in, and then the controller matches that URL up with an external_report URL in the DB.

**Comment by dougmartin** [comment]
@scytacki I made the changes you requested.

**Comment by scytacki** [comment]
Sorry @dougmartin I missed the `create_collabspace_template` before. This needs to be generic somehow too. 

One approach would be to add a "AuthoringSite" model. This model would have a Name and URL field. Then the authoring page would create buttons for each of these AuthoringSite models. When the button is clicked it would send the AuthoringSite model id to a controller action that would generate a JWT and append it to the URL and redirect.

**Pull request merged**
