### PR TITLE
Track round trip report time

### PR DESCRIPTION
**Pull request by knowuh**
Almost done with this work.  Some cleanup is still required before I ask for a review.

(I forgot to put in a PR for an earlier batch of work related to showing student status bars, for instance)

### CODE REVIEW

**Comment by knowuh** [comment]
There are two failing tests related to the hiding the progress bars and 'generate a report of my work'.  I will be looking at those soon.

**Comment by knowuh** [comment]
Its weird this test is still failing the "Show me a report of my work" test.  
It has been recently rebased on master which has the fix.  You can see the I18n code which fixed things [on this branch](https://github.com/concord-consortium/rigse/blob/track_round_trip_report_time/features/step_definitions/student_steps.rb#L87:   


   Then /^I should see a link to generate a report of my work$/ do
      text = I18n.t("StudentProgress.GenerateReport.NotDone")
      page.should have_selector("div.run_graph", text: /#{text}/i, visible: true)
   end

**Comment by knowuh** [comment]
I just realized this is an actual regression.  :/

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
