### PR TITLE
Rename Recent Activity page to Recent Updates.

### PR DESCRIPTION
**Pull request by knowuh**
Change the `Recent Activity` Page label to `Recent Updates`

[#159960718]
https://www.pivotaltracker.com/story/show/159960718

### CODE REVIEW

**Comment by knowuh** [comment]
@pjanik -- very small item for you to review :)

**Comment by knowuh** [comment]
@dougmartin I have burnt out @pjanik with PR requests. 😀  

Maybe you could look at this tiny change?

**Comment by dougmartin** [comment]
Looks good 👍

**Comment by pjanik** [comment]
Ops, I saw the notification in the morning but forgot to take a look at it before the meeting. It looks good. :wink:

**Pull request merged**
