### PR TITLE
WIP: Centralize pundit ahead of adding signin redirect

### PR DESCRIPTION
**Pull request by dougmartin**
DO NOT REVIEW - creating PR to allow Travis to run...

### CODE REVIEW

**Comment by scytacki** [comment]
@dougmartin looks like there is still one more failing test.

**Comment by dougmartin** [comment]
Yes and it was driving me crazy :)  The same post without xhr passes the test but with xhr it doesn't.  I talked with @knowuh to see if he new of any rails magic that might be altering the xhr request but he didn't know of any (and to be fair I kind of ambushed him about it in the middle of the day so the context switch was hard).  It is on my todo list today to resolve this.

**Comment by scytacki** [comment]
The helper method xml_http_html_request probably doesn't include the session (it isn't withCredentials).  So it probably goes through another code path.

**Comment by scytacki** [comment]
Looks good.

**Pull request merged**
