### PR TITLE
Schoology integration

### PR DESCRIPTION
**Pull request by psndcsrv**
* Use Schoology as an OAuth provider
* Provide a pre-flight landing page
* Provide a way to automatically trigger authenticating with schoology

### CODE REVIEW

**Comment by ddamelin** [comment]
Is this going to work with all of the other services (CODAP document server, LARA, etc.)? We are using Schoology as a PD platform in the Interactions project. Could teachers sign up for their Schoology account first and then log in to everything with that?

**Comment by scytacki** [comment]
Aaron based on what you said this morning, it sounded like you were going to work on this more. Is that right?

Dan, yes it should work but it should be tested. They can either login to the portal with their Schoology account. Or you can use our Schoology plugin so a link can be added to your Schoology course or groups, and then the portal is opened in an iframe inside of Schoology.

For ITSI purposes we will only be testing that it works with LARA, and we probably don't have time to fix any issues come up with the CODAP document server.

**Comment by psndcsrv** [comment]
@scytacki I'm going to fix the tests, but I think other than a possible UI link, I'm done. Unless we want to make sure the login process can be chained from a place like LARA, in which case it might require more tweaking (like, after logging in from Schoology it may not redirect correctly back to LARA).

**Comment by scytacki** [comment]
I can't think of a reason we need to chain it from LARA. We will be phasing out the idea of going to LARA directly to log in very soon. So teachers, students, and authors should all start the portal soon. And if the Schoology plugin is used then teachers and authors could also start at Schoology.

**Comment by psndcsrv** [comment]
Ok, cool. Because, yeah, I think if they're logged in to the portal already, then the other sites will probably authenticate fine. It was just the flow where the other site authenticating triggers them to log in to the portal that I wasn't sure would work. :)

**Comment by psndcsrv** [comment]
@scytacki Tests are now passing. The discussion about where to put a "Log in with Schoology" type link was not very conclusive, so that's not in there currently. But, this will allow the Schoology app to use the portal in the meantime.

**Comment by psndcsrv** [comment]
@scytacki I just tested (locally) LARA logging in via the portal, which logs in via Schoology. And it worked in both cases (surprisingly) - 1) where you've already signed into the portal via schoology and 2) where you haven't yet signed into the portal and you do it via schoology. So that's convenient.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
