### PR TITLE
WIP: 178193020 replace themes on rails gem

### PR DESCRIPTION
**Pull request by knowuh**

### CODE REVIEW

**Comment by knowuh** [comment]
Theme replacement work is ready now. I assigned to @dougmartin maybe @scytacki wants to have a quick glance too?  NBD, it ended up being a very small change with some tests and a lot of removed code.

**Review by dougmartin — APPROVED** [review]
Looks good :+1:

**Comment by knowuh** [comment]
@dougmartin  -- I added a few commits after your initial review, to clean things up and to handle mailer templates.

Probably the easiest way to review these would be to look at the individual commits:

* be08db1
* 55ba1ae
* 3e504a7
* bc89cd1

**Comment by dougmartin** [comment]
@knowuh Update commits look good :+1:

**Pull request merged**
