### PR TITLE
Fix student progress bar update

### PR DESCRIPTION
**Pull request by pjanik**
Progress bar is dynamically updated now (together with last run date and report link).
Some property names didn't match before and some information was missing (completion of the subsections / activities). I've used `Report::OfferingStudentStatus` for the Ajax update which is used by the regular view code on page (re)load, so hopefully things should be consistent.

### CODE REVIEW

**Comment by scytacki** [comment]
Can you review this for performance?  
When whole class of students have launched something, this status route is hit many times. Besides a geniverse route, this route is our most popular route. I think the previous code was just a single DB query for all the materials assigned to a student. It has an average response time of 20 ms. 
This new code looks like it has several database queries for each material assigned to the student. If you include the offering and the report_learner in the initial query that should help a bit. However there are still queries to look up all of the activities that are part of an investigation. As well as a separate request to look up the learner_activities from the learner. 
It doesn't seem like this could ever be as fast as it was before, but perhaps it can be improved to 4 total queries instead of something like 1+N*5

**Comment by pjanik** [comment]
Thanks, good catch. Right, I don't think we can get that as fast as it was, as simply the previous version was missing part of the data.

I've added `includes`. I was testing that locally and here are the queries:

1. [old student/status](https://gist.github.com/pjanik/8e9adcdba471029b2f1c)
2. [new student/status, no optimization](https://gist.github.com/pjanik/f5a6bb2794952e737d96)
3. [new student/status, optimized](https://gist.github.com/pjanik/eabb213b8c9af6017572)

Not perfect, but not sure if we can't easily optimize it more. Subsections of a material are pretty tricky, as there are many possible cases (old activity, old investigation, external activity, external investigation, etc.).

Two possible optimization I can think of:

- Track user actions and refresh only those offerings which were actually started (just just observe "Run" button clicks). I think it could save a lot of traffic. The problem is that if user refreshes page, we will lose this information and auto-update won't work anymore.

- Another optimization would be to send to Portal `last_run` date of each offering. Then Portal could quickly check if any offering has been updated (it seems that `last_run` is updated each time when a new answers comes from LARA) and only then return its status.

**Comment by scytacki** [comment]
This looks a lot better, but it still worries me. I rechecked what routes are taking most of the time on learn. This route isn't the highest right now, but I think with the current optimization it is going to become the second highest.
Of the two options the `last_run` approach seems the best. With no status updates it should be just as fast as before. Otherwise we'd expect only one activity to change at a time, so then it should prevent extra object loads when a student has several assignments.

**Comment by pjanik** [comment]
Done. I realized that I can send just one timestamp, so it made implementation simpler. In most cases Portal will return a new timestamp and an empty array.

**Comment by scytacki** [comment]
Looks great.

**Pull request merged**
