### PR TITLE
Removed unused code that used HashWithIndifferentAccess

### PR DESCRIPTION
**Pull request by dougmartin**
HashWithIndifferentAccess is soft-deprecated in Rails 5.1.  The file that used it is dead code along with one lib file used by that file (and their specs).

### CODE REVIEW

**Comment by dougmartin** [comment]
@scytacki should this be done on `master` since it is all dead code anyway?

**Comment by scytacki** [comment]
@dougmartin yeah I think anything we can do on master we should, just to spread any pain (from finding unexpected consequences) out over more weeks instead of all at the end.

**Review by knowuh — APPROVED** [review]
red == good

**Comment by dougmartin** [comment]
Closing to redo this on master

**Pull request closed without merging**
