### PR TITLE
Remove clazz student controller

### PR DESCRIPTION
**Pull request by scytacki**
Move the delete student (remove_student) action to clazzes_controller.
remove all of the student_clazzes_controller views and controller itself.
add specs of new action to clazzes_controller specs
also delete some partials that aren't used. references to them have been commented out for a while now

### CODE REVIEW

**Comment by scytacki** [comment]
@pjanik can you take a look at this one? I think the failing test is not related. It passed in the push build. Because it failed in the pull request build I can't look at the screen shots.

**Comment by pjanik** [comment]
I like the idea of removing the whole controller. I can see that the new action is just slightly modified version of an old one. There are some TODOs and FIXME, but it's an improvement anyway, so ofc I'm fine with merging.

However, this code accidentally includes things that are pretty annoying for me while working on Portal. Not saying it's important in this tiny example, but I'll mention that, as sometimes they're showing up in the new code too:

1. Do we really need all the render formats? I think that times where no-JS users should be supported are pretty much gone. I feel it's nice to have just one code path if we actually use only one. Might be easier to understand what's going on, find related views (if any) and easier to refactor. In this case it's not a big deal, but it seems that HTML format (and XML) are actually unnecessary, so at least we can get rid of one FIXME.

2. Redundant `@` assignments. It sounds like nitpicking, but I think it really builds up. I would just keep functions as "pure" as we can. Easier to refactor. Simple assignment to object property (`@`) in Rails have quite big consequences - given variable might be used in views, some filters / helpers, maybe descendant class or even tests. So, it changes quite a lot during refactoring (especially in language like ruby, where related error won't be detected statically). Well, later I noticed that most of these `@` vars are used by the JS view, but I'll mention that anyway, as it seems to be a case from time to time in a new code too.

**Comment by dougmartin** [comment]
This is a test for todo items in PR comments:

  - [ ] first item
  - [ ] second item
  - [ ] third item

**Comment by scytacki** [comment]
I was able to check off the first item.  
I looked at this PR as anon user and I could see the boxes and their state, but I couldn't check them.

**Comment by scytacki** [comment]
I never got this finished up. I'm closing it to keep the PR view cleaner.

**Pull request closed without merging**
