### PR TITLE
New sign up form

### PR DESCRIPTION
**Pull request by pjanik**
Replaces Angular-based signup form with a new version implemented using React.
Also, simplifies registration process - now ZIP / postal codes are expected instead of state / city.

This PR is pretty huge, but I've tried to divide it into 3 commits that can be reviewed separately.

1. Dependencies, probably not very interesting
2. API changes - biggest changes are in `teachers_controller`, since it can create a new school now (but I hope it's pretty clear and I've added specs)
3. UI implementation in React

There's one failing test, but I've noticed it's been failing for a while (even production releases).

A few questions:

1. `students_controller` isn't backward compatible. But I guess this API is used only internally by sign up. Is it okay to update it, or should be super strict and create a new version? If so, well, how should we do that? I've never actually fully understand what happens when we need to switch to version 2, since `/v1` is a prefix in our paths, not suffix. @knowuh or @scytacki?

2. <del>There was some logic related to anonymous / not-anonymous user in signup code: 
https://github.com/concord-consortium/rigse/blob/master/app/views/home/_signup.haml#L19
Is it fine to ignore it? Custom Learn home page effectively disabled it, as copy-pasted version of signup form didn't support it anyway.</del>

3. <del>I didn't clean up the old Angular code yet, because some import code is reusing parts of the Angular form logic: https://github.com/concord-consortium/rigse/blob/master/app/views/import/imported_login/confirm_user.haml
Do we still need it (@scytacki or @knowuh)? </del>

### CODE REVIEW

**Comment by pjanik** [comment]
Question 2 update: this logic was used to handle SSO sign up (e.g. Schoology) when basic `User` model has been already created, but we had to add Portal-specific models (`Teacher` or `Student`). I've reimplemented this in the last commit.

To test it locally:
1. Register a new teacher (or student).
2. Log in.
3. Delete `Teacher` (or `Student`) model using rails console (but leave `User` model!).
4. Go to: localhost:9000/portal/user_type_selector
4. Try to finish signing up.

This basically mimics Schoology use case without complicated setup.

**Comment by pjanik** [comment]
Question 3 update: user import and confirmation has been cleaned up, so I could remove Angular code.

I think it's ready to be reviewed now.

**Comment by scytacki** [comment]
I've only looked at the `schools_controller` change so far. I assumed that is what you meant instead of the `students_controller`.  I think it is ok to modify the v1 controller, however it is good excuse to think about how we would have to handle a new version.

The best article I found on this was:
https://www.mnot.net/blog/2012/12/04/api-evolution

We shouldn't make a new top level version for each individual controller change. The top level version should represent the whole collection of resources. So changing this would require duplicating a lot of routes and probably code too. Instead we should save top level version changes for fundamental API changes. So if we were going to keep backwards compatibility in this case I can think of few options:

1. make the existing v1 controller index action backward compatible
2. use content negotiation (the Accept header) so the client can specify it wants a different 'format' of the collection. 
3. make a new v1 controller with a different name
4. make a second index action on the v1 controller

Of those choices, in this case, I'd vote for *#*1 'make existing action backward compatible'. 
*#*2 (content negotiation) isn't right because we aren't changing the format, we are changing the required parameter. 
*#*3 would create more duplicate code or more complex code with modules or inheritance.
*#*4 would require a new URL that would not follow our normal conventions.

The reasons for not making a single new `v2` controller are:
- some URLs would have `v1` and some URLs would have `v2`
- if we had documentation we could not have a simple top level `v1` and `v2` documentation section. We'd have to have different versions for each route or resource. 

Just for completeness if we did make a full new version of the API we'd have to copy things to new v2 folders:
- the controllers
- the helper models (semi presentors)
- policies
- tests

There would probably be a fair amount of duplicate code, so it might be good to use inheritance or modules to remove the duplication. Ideally the tests for v1 would be unchanged so we can verify that this refactoring would cause no problems.

But to re-iterate what I said above, I think it is best in this case to just make the breaking change like you have already done.

cc @knowuh - for a good read when you are back from vacation :)

**Comment by scytacki** [comment]
Looks good to me. 👍  
Hopefully we can clean up the javascript dependency management and module loading soon.

**Pull request merged**
