### PR TITLE
150539624 secure teacher class

### PR DESCRIPTION
**Pull request by jsimpson-cc**
Prevent teachers from accessing classes that belong to other teachers, and setting bookmarks on classes that do not belong to them.

### CODE REVIEW

**Comment by jsimpson-cc** [comment]
Need to confirm travis tests are working.

**Comment by scytacki** [comment]
Looks like a few test failures.
A few comments:
- I'm trying to phase out use of current_visitor. The standard Rails method is current_user. current_user is nil if there is no user logged in.  Our current_visitor method returns a fake user if no one is logged in. So to switch to current_user you should check for nil if the code is going to run even for anonymous users.
- we tried to switch everything over to Pundit, but didn't have time to update the clazzes_controller. It is probably too much work to do that now. But I think the bookmarks_controller could use Pundit. A good example of a Pundit Policy is this file: http://github.com/concord-consortium/rigse/blob/eba81f942c90c25542c54527d47228913559f7ee/app/policies/portal/offering_policy.rb it has a method that checks if the current user is a teacher of the class of the offering. A rule of thumb I try to follow for the pundit policies is to keep them mostly self contained. This makes it easier to see what rule applies to what controller action without looking through several files. In other words I've tried to avoid using class hierarchies or includes to consolidate common actions. So this means there is some duplicate code, but I think it makes it easier to maintain. If we could get full Pundit coverage, then we could turn on error checking so new controller actions will automatically throw an error if they don't have a pundit policy.

**Comment by jsimpson-cc** [comment]
Cucumber tests are still failing. I will make the changes you suggest above.

**Comment by jsimpson-cc** [comment]
>  I think the bookmarks_controller could use Pundit

From what I have been learning about pundit policies they are tied to models and not controllers.
So for the `BookmarksController` to call `authorize` on a model of type `Clazz`, there would need to exist a `ClazzPolicy` (we have one, it is empty) which would in turn define methods that exist in the `BookmarksController`. I.e. index, add, add_padlet. Which seems confusing because if we were to then go and add pundit calls to the `ClazzesController` it seems like there could be conflicts e.g. `index`. Also you are not calling `add` to add a class, rather you are calling `add` to add a bookmark. 

Is this what we want? Or have I misunderstood?

```
class Portal::ClazzPolicy < ApplicationPolicy

  def index
    user && record && record.is_teacher?(user)
  end

  def add
    user && record && record.is_teacher?(user)
  end

  def add_padlet
    user && record && record.is_teacher?(user)
  end

end
```

**Comment by jsimpson-cc** [comment]
Tests are fixed. @scytacki See comments on pundit and let me know what you prefer.

**Comment by scytacki** [comment]
Since there is a Bookmark model, I think it would make sense that there would be a BookmarkPolicy. 
It could be used after the Bookmark model has been initialized before it is saved. So for example just before this line:
http://github.com/concord-consortium/rigse/blob/b11dca8776995a7807b6c1d1a894732b02e42ce8/app/controllers/portal/bookmarks_controller.rb#L29
You could call: 
`authorize mark`
Which ought to look for an `add?` method in the Portal:GenericBookmarkPolicy
And the `record` that is available to the `add?` method will have the class set on it so that class can be used to decide if the user should be able to create this bookmark.

In this BookmarkPolicy approach I'm not sure how best to handle the index action. One way would be to use a Scope. This Scope would limit the bookmarks just to ones associated with the current user's classes. But this would require doing a lot of DB queries to get this list of classes. When really all we need to do is check that the passed in class is valid.  So perhaps the best approach is something like this:
`authorize @portal_clazz, :list_bookmarks?` 

Alternatively you could put all of methods in the ClazzPolicy. So like above, the method name that is checked in the policy can be overridden. So the add checks could be done with `authorize get_current_clazz, :add_bookmark?`

I'll leave it up to you to pick an approach.

One that you should make sure to check that students still see their bookmarks in their class.

**Comment by jsimpson-cc** [comment]
This still needs to be tested. I think I missed this. 

> Just to be sure, you should check that students still see their bookmarks in their class. If you use the Scope approach that might require allowing students to see bookmarks for their classes in addition to teachers.

**Comment by jsimpson-cc** [comment]
Yeah the student view of the bookmarks is fine, since it comes from the classes view.

**Pull request merged**
