### PR TITLE
178168630 copy itsi items

### PR DESCRIPTION
**Pull request by emcelroy**
PT Story: https://www.pivotaltracker.com/story/show/178168630

[#178168630]

### CODE REVIEW

**Comment by scytacki** [comment]
@emcelroy can you merge master into this branch? The PR is showing differences that were included in this PR https://github.com/concord-consortium/rigse/pull/1065/files and have already been merged in.  I think by merging master the changes listed in this PR will decrease.

**Comment by emcelroy** [comment]
@scytacki Sure. I've merged master in. Sorry, I thought I had done that already, but apparently I didn't.

**Comment by scytacki** [comment]
For some reason the build of this was canceled. I just restarted the build.

**Review by scytacki — APPROVED** [review]
Looks good to me.

**Pull request merged**
