### PR TITLE
Add more stats to the class student roster  [#103127914]

### PR DESCRIPTION
**Pull request by knowuh**
In order to help teachers identify active and non active students, add more stats to the class student roster.

Columns:
| Name |  Username | Last Login | Assignments Started |

Because there were a number of loops and calculations in the view, I extracted `student_roster_row.rb`.

Also I18n'd the strings, created some tests, and modified styles to accommodate more info in the table row.

We don't have a nice folder structure for view-models like `student_roster_row.rb` -- there are other instances of these kinds of objects, but they all sit at the root of `models`.  

https://www.pivotaltracker.com/story/show/103127914

### CODE REVIEW

**Comment by knowuh** [comment]
@scytacki I keep bugging you for PRs.  Do you think I should pull in Doug or someone else?

**Comment by scytacki** [comment]
No it is fine to bug me about these. :)
My only concern would be performance. We do have one teacher that has 100 students in their class.
Did you look at the how the student_list is created? If it isn't using `includes`, then using that might help (depending if various relationships are setup correctly) to avoid extra database queries. 
Perhaps for for abstraction you might want a roster object that can encapsulate this efficient query and provides a list of roster rows.

If you don't think it is an issue, then don't worry about it. We don't need to over optimize.

**Comment by knowuh** [comment]
I followed your advice @scytacki and wrote a student_roster which eagerly fetches the associated student -> learner -> offerings (and student -> user) relations.

Its a little cleaner, and should eliminate n+1 issues we had earlier.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
