### PR TITLE
176661412 questions out of order report

### PR DESCRIPTION
**Pull request by knowuh**
This is ready for a review.

The PT Story: https://www.pivotaltracker.com/n/projects/2441249/stories/176661412

## Steps to reproduce
- Download a details report for any sequence
- Compare question order in the downloaded report to question order in the activities
## Expected
- Question order in the downloaded report should match the question order of the activities.
## Actual
- Question order in the downloaded report does not match the question order in the activities. Additional information detailed in this Slack thread.

Summary:  When we updates to Rails 4, there was an update to the acts-as-list gem.  In our publication code, we were setting the position attribute to "0" which is *not* the top-of-list by default, see: https://github.com/brendon/acts_as_list#more-options

bdf9d60 created a failing test expaction
c666b9e fixed the publication code to index pages and page elements starting at 1, which fixed the test failure.

A local details report I had run previously had incorrect question numbers.  After republishing with the code fix, the report had questions in the correct order.

### CODE REVIEW

**Comment by knowuh** [comment]
Here we see the test failing:
Screen Shot 2021-04-27 at 5 39 07 PM

**Comment by knowuh** [comment]
OK the tests are passing now, and after I republished my sequence, I am seeing my report Items in the correct order locally.

Screen Shot 2021-04-28 at 2 13 20 PM

**Review by scytacki — APPROVED** [review]
Looks great to me.

**Comment by scytacki** [comment]
@knowuh I see this is still in the draft state.

**Comment by knowuh** [comment]
@scytacki sorry about that, ready for review now.

**Pull request merged**
