### PR TITLE
New unison approach

### PR DESCRIPTION
**Pull request by scytacki**
this uses unison inside of a container to sync two volumes.  The first volume `UNISON_HOST_DIR` is mounted as a standard docker bind mount.  That `UNISON_HOST_DIR` gets sync'd to the `UNISON_DIR` which is a named volume that is shared with the app container.  This isolation of the two volumes allows the app container to run at full speed.

### CODE REVIEW

**Comment by scytacki** [comment]
@dougmartin you should give this a try. I'm pretty sure it will work on windows too. And I suspect it will really speed things up.  You need to add the docker-compose-sync.yml into your .env COMPOSE_FILE list.   You also need to rebuild the app container with a `docker-compose build app`.

**Comment by scytacki** [comment]
@knowuh you might be interested in this one as well.

**Comment by knowuh** [comment]
cool, I will give it a try.

**Comment by knowuh** [comment]
This works well for me. 

Access the app server on my local machine is way faster. Guard works too, so I can just run `docker-compose exec app docker/dev/run-ci.sh` and tests run when I save changes in my editor.  

👍

**Comment by dougmartin** [comment]
👍  Much, much, much, much faster now on Windows.  The only downside for me is the amount of sync messages that stream in the window running Docker.  I sometimes do `puts` style debugging so maybe this will force me to get interactive debugging working.

**Comment by scytacki** [comment]
@dougmartin you can open a new terminal and run `docker-compose logs -f app` that will stream the logs just from the app container.

**Pull request merged**
