### PR TITLE
Fixed saves of projects in portal settings form [#176035653]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
@scytacki i fixed the broken Travis test yesterday.  The test json had a hardcoded id of 12.  When the tests run on Travis the id of 12 already exists in the database due to previous tests but when run locally it does not.  I increased the id in the test json to 1000.

**Review by scytacki — CHANGES_REQUESTED** [review]
@dougmartin we figured out before this approach would cause problems when a project admin can only see a subset of the projects.  https://concord-consortium.slack.com/archives/D048JG9FA/p1607435390002600 
If the external_activity is already associated with projects which the current project admin doesn't have access to, the update action will remove those existing projects and replace them just with what the project admin can see.

I found some example code that needs to solve the same problem. The users controller has to do this with the project admin and project researcher roles: https://github.com/concord-consortium/rigse/blob/7aae391ef2f49b162cf600bd865f39a18492b038/rails/app/controllers/users_controller.rb#L163-L168

For project admins, it finds all of the possible projects the current user might be able to modify: `current_visitor.admin_for_projects`. Then it passes that as the `possible_projects` param to `set_role_for_projects`:
https://github.com/concord-consortium/rigse/blob/7aae391ef2f49b162cf600bd865f39a18492b038/rails/app/models/user.rb#L458-L466
Which then goes through the possible projects and updates each relation just for those possible projects.

Did I forget some part of this, which makes it unnecessary do that?  Perhaps project admins see all projects but some options are grey'd out and can't be changed. And these options are still sent up to the update action?  That wouldn't be secure, but at least it wouldn't clobber previous project settings.

**Comment by dougmartin** [comment]
@scytacki after looking at this again I found existing code that Piotr added 5 years ago to handle keeping the non-visible projects assigned:

https://github.com/concord-consortium/rigse/pull/915/files#diff-1f2d5c8346b0f0c368b1008836ac60efc66b7ebe7d627d956aa220f703aa48deR17-R19

**Review by scytacki — APPROVED** [review]
OK, seems fine to me then.

**Pull request merged**
