### PR TITLE
let external activity owners edit some settings

### PR DESCRIPTION
**Pull request by scytacki**
in ITSI authors need to set the publication status as well as
the grade level and subject area
#111712272

### CODE REVIEW

**Comment by scytacki** [comment]
@pjanik or @dougmartin could you take a look at this one?

Piotr made some changes to restrict the edit pages of external activities. But this ended up restricting authors from using the 'short form' of editing which they use to change a few properties of the external activity.  This 'short form' of editing is available from the 'edit resource options' button on the `matedit?iframe=true` page of external activities (accessible from the edit button on the search page).

**Comment by knowuh** [comment]
I gave this a quick look.  I don't understand all the details, but nothing seemed crazy to me.

**Comment by scytacki** [comment]
I want to try to get this tested by Evangeline today, so I'm going to merge this.

**Comment by pjanik** [comment]
Sorry for late answer. Looks good to me, however I was a bit surprised that it works, as I remember I also restricted edit link rendering here:
https://github.com/concord-consortium/rigse/blob/master/lib/materials/data_helpers.rb#L74
But it seems that this value is ignored anyway and the logic that is actually used is a bit lower:
https://github.com/concord-consortium/rigse/blob/master/lib/materials/data_helpers.rb#L168-L179
I could clean it up, but not sure about status of testing.

**Pull request merged**
