### PR TITLE
Add extra links in the menu bar per project [#94411134]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
I'm fixing the spec failure.

**Comment by dougmartin** [comment]
The spec failure has been fixed.  The cucumber failures are unrelated to this change.

**Comment by scytacki** [comment]
Looks good. 
Can you add a test that verifies when a user is associated with a project then they see the links for this project. This could be a cucumber test or it could be a integration spec test.

**Comment by scytacki** [comment]
I'm going to go ahead and merge this, and we can work on the test later.

**Pull request merged**
