### PR TITLE
Fix permission_form searching

### PR DESCRIPTION
**Pull request by knowuh**
Use permission form IDs when selecting learners in the researcher reports.

As per [131178067](https://www.pivotaltracker.com/story/show/131178067):

The report filtering was searching the `Report::Learner` flattened `permission_forms` field which stored the names of permission forms for the learner.  The original problem was that the permission form storage and searching used different formats for the name (one used the project name as part of the permission form name.)

So instead, we now search on the student model directly, using the ID of the students `permission_forms` .

Some spec tests were added to cover these cases.

### CODE REVIEW

**Comment by knowuh** [comment]
@scytacki  the failing cuke test is the usual suspect.  Have a look when you get a moment?

**Comment by scytacki** [comment]
I have two worries, but I don't know if they are well founded or not.  

1. The active record joins method is an inner join. Which means if the same student has two permissions forms from the filter list, then the student will probably show up twice in the results. This might be solved by adding a `.distinct` to the end of scope, but it would probably be good to test this issue first. Or perhaps somewhere else in the code is making sure the student/learner is unique. I think we consolidate learners down into one row per student. And I think we combine together the learner ids with commas into one cell. So I think if there are multiple copies of one learner this cell might just end up with duplicate ids.

2. Not using the report learner might slow things down.  However I'm pretty sick of our report_learner object. It is annoying to have to worry about keeping it updated when we make changes like this.  So I think if there is a slow down, it is OK as long as it isn't too severe.  Perhaps an easy way to test this is to deploy it to staging and then see if there is any difference filtering the report with and without permission forms.

**Comment by knowuh** [comment]
I think your first concern is a good point. I will writes some tests to ensure that we only return one learner object.

Yeah, and Item #2 worries me a bit too. This partiuclar join scope is being dynamically applied to the Report::Learner query after all the other filter scopes. Also it is only being applied if a permission form filter has been specified. If this is the only filter specified, I guess it could be a longish query.   

As you say, we could run the query on staging, and then manually on learn after hours and see how it does.

**Comment by knowuh** [comment]
I added some tests in [#953fe18] that were failing with the old `joins()` scope as you suggested.  Then I wrote some specific finder_sql to do the joins by hand to get the tests to pass. I was able to cut out one join in the process.

**Comment by knowuh** [comment]
I discovered a problem with this approach.  `find_by_sql` returns an array instead of a relation, which will cause other queries to fail.  :(

**Comment by knowuh** [comment]
@scytacki I think we have to stick with `.includes` for now.  It mostly does the right thing. It loads more model into memory but  ¯\_(ツ)_/¯

**Comment by scytacki** [comment]
Looks good. 
I think it would be possible to use inner join here with `distinct`, but lets go with with includes for now.

**Pull request merged**
