### PR TITLE
Speed up CC-Reporter Stage

### PR DESCRIPTION
**Pull request by nvick**
This PR cuts the CodeClimate stage down to ~1 min. It adds conditionals on `before_script` commands to make sure they are only run on the Test stage.

### CODE REVIEW

**Comment by scytacki** [comment]
Instead of conditionalizing every line, it might work to just redefine the `before_script` in the cc-reporter job.

**Comment by scytacki** [comment]
I saw you tried to skip the before_script in one of the commits and that didn't seem to work. But if you redefine it, that seems like it might work. At least in this blog post it is defined within the job definition, so I'd assume it could be overriden: https://blog.revathskumar.com/2016/11/travis-override-vm-in-matrix.html

**Comment by nvick** [comment]
I agree I wasn't happy with the solution. It seemed like I should be able to override the before script, but was unsuccessful in my attempts. I'm glad to take another look at it though.

**Comment by scytacki** [comment]
If overriding the script doesn't work, then I'd suggest pulling the script out to a seperate file. Then you use a single conditional.

**Comment by nvick** [comment]
After a few attempts I decided to move the test setup to a script.

**Comment by scytacki** [comment]
👍

**Pull request merged**
