### PR TITLE
Country list update

### PR DESCRIPTION
**Pull request by emcelroy**

### CODE REVIEW

**Comment by scytacki** [comment]
Did you test that initializing the database using the seeds.rb still works?
That is the way we ought to be doing initializing new databases instead of always re-running the migrations.  It is what the local docker setup will do if you start from a clean checkout. It is doing it here: https://github.com/concord-consortium/rigse/blob/ecfb524af69ababadc154220418e4ed29bac8db7/docker/dev/run.sh#L37

I suspect it works, because seeds.rb calls: https://github.com/concord-consortium/rigse/blob/ecfb524af69ababadc154220418e4ed29bac8db7/db/seeds.rb#L165 

What happens if user chose a country already and now we've imported additional countries with the same code?  Are they going to continue to see the same country?  It seems like this, but I just wanted to check.

Did you try running the migrations on a clean database? There is this old migration that assumes the old file exists: https://github.com/concord-consortium/rigse/blob/ecfb524af69ababadc154220418e4ed29bac8db7/db/migrate/20140908150149_populate_school_countries.rb#L21 

Where did you get the new file? Did you find a place to download it?  It would be good to add a new md file in the docs folder with info about where and how you got it.

**Comment by emcelroy** [comment]
The new data file is the one we found at https://datahub.io/core/country-codes

I'll add a file about it to the docs folder.

**Comment by emcelroy** [comment]
@scytacki @knowuh Actually, I may have misinterpreted the licensing of the data. What do you make of the information under "License"?

https://datahub.io/core/country-codes#license

ISO says "ISO makes the list of alpha-2 country codes available for internal use and non-commercial purposes free of charge" which I would read to mean non-commercial _public_ use is OK. But the maintainers of this particular data file then say "If you intended to use these data in a public or commercial product, please check the original sources for any specific restrictions" which suggests public non-commercial use may be restricted.

I'll try to find out anything more I can about that, but please let me know if you have thoughts on how we should interpret that. I wonder specifically if you consider our usage of the data to generate a list of countries for the portal as public use.

**Comment by emcelroy** [comment]
@scytacki: I put back the old country data csv file for now to avoid breaking that old migration. I also tested initializing the database using the seeds.rb and that appears to work OK.

Regarding the question about a user that chose a country already continuing to see the same country etc., Noah said "We tried this, and yes, its fine."

I think the latest commit makes this ready for testing. Please let me know if there's anything I missed though. Thanks.

**Comment by scytacki** [comment]
Looks good to me.

**Pull request merged**
