### PR TITLE
Convert find(:all...) references to Rails 4 syntax

### PR DESCRIPTION
**Pull request by tjchambers**
Address the `find(:all`syntax by transforming it to `all` or `where...` usage which is Rails 4 compatible.

### CODE REVIEW

**Comment by tjchambers** [comment]
@scytacki leaving this in pending state till you decide if you want me to address the `imports_controller` and `nces06_districts_controller` references. There are 6 that are not spec covered, but are simple.

**Comment by tjchambers** [comment]
I will take a look and perhaps break them again so I can see how easy it is to encourage cover. Thanks.

**Comment by tjchambers** [comment]
Ready for re-review. 

Have extended code coverage everywhere. Also noted that `learner` and `offering` somehow missed the code coverage expansion process for unknown reason, so I expanded those. The others mostly needed some corrections to existing specs that were marked `xit`.

**Comment by scytacki** [comment]
Woohoo. We are up another percentage point of coverage (with rounding).  
👍

**Pull request merged**
