### PR TITLE
150971692 fix related resources query

### PR DESCRIPTION
**Pull request by jsimpson-cc**

### CODE REVIEW

**Comment by jsimpson-cc** [comment]
This check for assessment doesn't seem to be working. Doing more testing now.

**Comment by jsimpson-cc** [comment]
Forgot to reindex sunspot. This is working to exclude the is_assessment_items. So that's correct.

**Comment by jsimpson-cc** [comment]
This is what confuses me about the admin role check.

`any_of` is "or" right? (And default is "and"?) So should the following:

```
                any_of do
                    with    :published,     true
                    with    :user_id,       user_id
                end

                if ! current_user.nil?
                    if ! current_user.has_role? ['admin']
                        any_of do
                            with    :cohort_ids,    nil
                            with    :cohort_ids,    cohort_ids
                        end
                    end
                end

```

Instead be something more like:

```
                any_of do
                    with    :published,     true
                    with    :user_id,       user_id

                    if ! current_user.nil?
                        if ! current_user.has_role? ['admin']
                            with    :cohort_ids,    nil
                            with    :cohort_ids,    cohort_ids
                        end
                    end

                end

```

**Comment by scytacki** [comment]
Yes the default is 'and'.  I think the logic in the current PR is not right. What we want is for published materials that have a cohort tag to be hidden for anonymous users and hidden from any user that isn't part of that cohort. This should be what the main search is doing.  

For testing locally, if you make a ExternalActivity published and tagged with a cohort, and then view the search results anonymously you should not see it.  And if you view the search results as a teacher that is not part of that cohort, you also not see it. 

In the current code of the PR, the cohort based filtering is only applied if the user is not anonymous.  Which would mean an anonymous user will see materials tagged with a cohort because nothing is filtering them out. 

In your replacement code above, if the material was published then the rest of the conditions would be skipped because `any_of` is building an OR statement to be sent off to Solr.

I think perhaps you are not realizing that there is both a query building step and then a query executing step.  I'm making those terms up, I don't think they are official sunspot language.  And the logic for both of these steps is mixed together. So the `if` and `else` logic is during building step, and the `with` and 'any_of` is logic run during the execution step. 

So to make this work I was thinking something like this:
```
any_of do
  with    :published,     true
  with    :user_id,       user_id
end

if current_user
  if ! current_user.has_role? ['admin']
    any_of do
      with    :cohort_ids,    nil
      with    :cohort_ids,    cohort_ids
    end
  end
else  # user is anonymous 
  with  :cohort_ids,    nil
end
```

This way the query that is built when an anonymous user access the search, has a condition that all materials have to have no cohort_ids.

**Comment by scytacki** [comment]
👍 Lets give this a shot. I'll get it up on staging later today.

**Pull request merged**
