### PR TITLE
Remove Logstash, update ElasticSearch models directly on learner changes

### PR DESCRIPTION
**Pull request by sfentress**
This removes the Logstash Docker container and makes the Portal::Learner class responsible for updating ElasticSearch. It also adds the field `created_at` to the ES models, which will be important for later sorting of learners.

There is also a new Rake task, `app:report:update_elastic_search_learners`, which will find all learners and push them to the database. Because the ES operations are doing using "upsert," this will create docs if they don't exist and update them if they do, which means that the task is safe to run over an existing database.

The tests broken by this took quite a while to fix, and there is still one (or more, we'll see after this finishes building) failing test, `./spec/models/dataservice/process_external_activity_data_job_spec.rb:91 # Dataservice::ProcessExternalActivityDataJob#perform perform`, which I can't even work out what it does, so some advice there will be helpful.

### CODE REVIEW

**Comment by sfentress** [comment]
> there is still one (or more, we'll see after this finishes building) failing test

I knew I was tempting fate to say that before the build ended.

It seems that my WebMock reset may have broken a bunch of tests, which is odd because that didn't seem to happen locally, although maybe I was doing steps out of order.

I'll mark this PR as draft, although if either of you has any advice for the `./spec/models/dataservice/process_external_activity_data_job_spec.rb:91` test, that would be helpful

**Review by kswenson — COMMENTED** [review]
The additional comments make sense, even though most of the technologies involved are alien to me, which seems like a good sign. :wink:

**Comment by sfentress** [comment]
Other tests fixed, only one is the mystery `./spec/models/dataservice/process_external_activity_data_job_spec.rb:97` which I don't understand.

**Review by scytacki — APPROVED** [review]
This looks good to me.

It is going to have a lot of merge conflicts when it is brought into the rails6 branch.
So I think it is best to pair with @knowuh when you both are available to get this merged into rails6.

**Pull request merged**
