### PR TITLE
Fixed cursor jumping in text input [#173795059]

### PR DESCRIPTION
**Pull request by dougmartin**
Before this change any update to the text input value would cause the cursor to jump to the end of the line.  This was new behavior caused by the update to React and Formsy.

With this change the cursor position is remembered and then restored after the text input's controlled input value is updated in the state.

### CODE REVIEW

**Comment by dougmartin** [comment]
@kswenson the code (taken from StackOverflow) is pretty elegant.  I tested it out before commiting and when you have a range selected and you update the range it collapses and but the selection start moves past the insert so then setting the end to the start sets the cursor to the newly inserted text after the collapsed range.  It works for both single key input and pasting multi-character strings.

**Comment by pjanik** [comment]
I'm not familiar with selectionStart/End props and never seen this approach necessary. But if it helps, it seems fine.
I'm a bit surprised that we set `selectionEnd` to `selectionStart` in fact. Is this intentional? If so, some comments could be useful so someone doesn't "fix" it.

**Comment by dougmartin** [comment]
@pjanik / @kswenson I've added a comment in the code about why `selectionEnd` is set.

**Comment by kswenson** [comment]
👍 
>the code (taken from StackOverflow)

When using code from SO I find it helpful to include a link so that anyone coming back to this code down the road can review any relevant discussion around the change.

**Pull request merged**
