### PR TITLE
Fixed missing mysql_creation_options function in feature_test prepare rake task [#174946131]

### PR DESCRIPTION
**Pull request by dougmartin**
This looks like it wasn't added in a recent change to the rake task.

### CODE REVIEW

**Comment by dougmartin** [comment]
NOTE: this can't be tested on Travis until this PR is merged: https://github.com/concord-consortium/rigse/pull/852

**Comment by dougmartin** [comment]
@knowuh I rebased this PR onto the other PR so I can see the test running in Travis.  This PR should still wait for the other one to be merged.

**Comment by dougmartin** [comment]
@scytacki I tagged you for this too as this is the area of code you updated a few weeks ago.

**Comment by dougmartin** [comment]
I set this back to a draft so that it isn't merged before the PR is it based on is merged.

**Review by knowuh — COMMENTED** [review]
Note: #852 has been merged.  This PR looks good to me.

**Comment by dougmartin** [comment]
I've rebased it back on `rails4` to remove the unneeded code.  Merging.

**Pull request merged**
