### PR TITLE
Authored by me

### PR DESCRIPTION
**Pull request by sagartalla**

### CODE REVIEW

**Comment by scytacki** [comment]
If I'm reading the code right, if a user checks off the "authored by me" box they will no longer see the published materials even if that "official or community" boxes are checked. I'll put a note in the story about all this. I'm not sure the best approach.

Because this isn't obvious what should happen please start writing some cucumber tests, so we can keep it working whichever way we decide.

**Comment by scytacki** [comment]
Are the cucumber tests passing locally for you?

**Comment by sagartalla** [comment]
@scytacki When we run  `cucumber features/authors_can_filter_their_own_material.feature` individually it is passing. 
But when we run all the tests using the command `cucumber`  `authors_can_filter_their_own_material` is failing. Here is the capybara screenshot for the failing test

screenshot_Authors-can-filter-Interactive-using-authored-by-me_2015-05-27-14-54-32.960.png
screenshot_authors-can-filter-interactive-using-authored-by-me_2015-05-27-14-54-32 960

**Comment by scytacki** [comment]
It sounds like we need to work on our integration of Cucumber and Solr/Sunspot. 
@psndcsrv when you got cucumber working again, did you do something special to make Sunspot work with it?  
I found this old post: http://collectiveidea.com/blog/archives/2011/05/25/testing-with-sunspot-and-cucumber/  which talks about a `sunspot_test` gem, but it is very old now.

cc @pjanik @dougmartin

**Comment by psndcsrv** [comment]
@scytacki @sagartalla I think rather than sunspot not being started (which happens automatically as part of all the cucumber setup), the "unavailable" message is masking an exception being thrown by sunspot. I had put that try/catch block and message display in there assuming that the exceptions we'd see from sunspot would be because the backend isn't running, but I think in this case it's throwing an exception for other reasons.

We should probably modify that try/catch so that we can more easily know what the error actually was.

**Comment by psndcsrv** [comment]
And, as an aside, in production seeing that message would still trigger an exception notifier email. Maybe we need to have the cucumber tests save the mail queues as artifacts to S3.

**Comment by scytacki** [comment]
It might work to just upload the full test server log file to S3.

My guess on the exception, is that it is related to how we are essentially clearing the database after each test. I bet we are not clearing/reindexing Solr after each test.  So it is possible Solr will have stale things in it after a previous test runs. I'm not sure what the solution to this is.

**Comment by sagartalla** [comment]
@scytacki We tried run the tests by removing the try/catch here https://github.com/concord-consortium/rigse/blob/master/app/controllers/search_controller.rb#L32 and we got this error https://gist.github.com/sagartalla/e00fb947db04bab10161 

It is failing here 
https://github.com/concord-consortium/rigse/blob/master/app/models/search.rb#L162. It is getting `facet.instance` as nil.

Looks like solr is having stale instances of `Investigation` from this test https://github.com/concord-consortium/rigse/blob/master/features/admin_works_with_projects.feature.

Re-indexing the `Investigation` model before the test seems to fix the failing test in this branch locally.

**Comment by scytacki** [comment]
Did you have any luck finding tools to help with integration testing combined with Solr?  
I just found this post: http://ricardomerizalde.blogspot.com/2012/12/integration-testing-with-solr.html
It is for Java, but if we could find something similar for cucumber that would be great.  Otherwise we'll need to re-index Solr between each test. In that post they describe creating a read-only Solr and then making copies of it when it is necessary for the test to modify Solr.

At least we could try to use the gem that I mentioned before, which is described here:
http://collectiveidea.com/blog/archives/2011/05/25/testing-with-sunspot-and-cucumber/ 
Did you give that a try?

**Comment by sagartalla** [comment]
@scytacki Yes we are current working on sunspot_test, We'll update when its done.

**Pull request merged**
