### PR TITLE
Changed add/remove favorite routes to POST from GET

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
Sorry for the noisy diff - my editor automatically trims trailing spaces.

**Comment by scytacki** [comment]
There are usages of this API in the portal that I think also need to also be updated.

**Comment by jsimpson-cc** [comment]
> There are usages of this API in the portal that I think also need to also be updated.

Right.
./app/assets/javascripts/components/search/material_icon.js.coffee

**Comment by jsimpson-cc** [comment]
Not sure on the status of portal pages but if we are still requiring the existing react components work in advanced search and favorites views, then that javacriot should probably be fixed as part of this change set.

**Comment by scytacki** [comment]
Yes it should be part of the change set. Doug is almost computer-less to day do to being at CC without a power adapter and hoping to save his battery for the demo this afternoon.

**Comment by dougmartin** [comment]
Sorry, I should have looked - I thought this was just a pure API addition for the new portal redesign.

**Comment by scytacki** [comment]
I'm going to leave this un merged for the demo meeting today.   So the favorites work in the portal-pages components won't be working (unless Doug changes it).

**Comment by scytacki** [comment]
@jsimpson-cc can you finish up this PR for @dougmartin, by modifying the material_icon.js.coffee ?

**Comment by jsimpson-cc** [comment]
> @jsimpson-cc can you finish up this PR for @dougmartin, by modifying the material_icon.js.coffee ?

Will do.

**Comment by jsimpson-cc** [comment]
Changed the jQuery ajax calls to use the POST method, though this was actually working using the default GET as well.

**Comment by scytacki** [comment]
So sending a get request to the routes that are now marked `post` in routes.rb still works?  That seems odd.

**Comment by jsimpson-cc** [comment]
Seemed odd to me too. But I went ahead and changed the client calls anyway.

**Pull request merged**
