### PR TITLE
Moved resource lightbox to the top of the page [#151009073]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
Moving the auto show lightbox to the top of the page does not interfere with the other dynamic lightbox code.

**Comment by dougmartin** [comment]
I didn't touch the footer injection code because it has no effect on the SEO of the page.  It only gets used when you land on the homepage and then click on a resource.  I did verify that the injection code still works with this change.

**Comment by scytacki** [comment]
I would like to keep this as similar as possible. When they are different it is easy to make changes to the styling or behavior of one and forget about the styling or behavior of the other. This already bit us once so I moved everything down to the bottom to keep it uniform.

**Comment by scytacki** [comment]
Closing this for now, feel free to reopen.

**Pull request closed without merging**
