### PR TITLE
Project admin can mark an activity  as CC official.

### PR DESCRIPTION
**Pull request by knowuh**
[#113925649]

https://www.pivotaltracker.com/story/show/113925649

### CODE REVIEW

**Comment by scytacki** [comment]
The first commit should be all you need to do. The second commit adds a redundant check that almost matches what is in edit_settings policy: https://github.com/concord-consortium/rigse/blob/master/app/policies/material_shared_policy.rb#L7-L11 
and adds a test that claims to be the opposite of the goal of the story.

After looking at this for a while, I think I understand the root of the problem.  The test that failed on the first commit is actually wrong. https://github.com/concord-consortium/rigse/blob/project_admin_changes_official/spec/views/external_activities/edit.html.haml_spec.rb#L18

It is only stubbing current_visitor. It doesn't also stub current_user, so the current_user is still an admin based on the before(:each). The policy check uses current_user, so it will return true since the current_user is an admin.

The new test is also broken. It creates an auth_user object but then stubs current_visitor not with the auth_user but with a new author. It should stub current_visitor and current_user with the auth_user that it created.

**Comment by knowuh** [comment]
If its true that any logic in the form is redundant because of the controller policy, then I suggest we remove the view test completely.

**Comment by scytacki** [comment]
The controller doesn't determine which properties are visible. There is a check in the view using the policy to see if the current_user has access:
https://github.com/concord-consortium/rigse/blob/master/app/views/external_activities/_form.html.haml#L4

So I think it is worth keeping the test.

**Comment by knowuh** [comment]
I am re-running the failing test here.  I can't believe its related.  `expected there to be content "Show Notices" in "Rails Portal (development)\nWelcome joe user\n`.   Otherwise :+1:

**Pull request merged**
