### PR TITLE
Fix reset_password API response message.

### PR DESCRIPTION
**Pull request by jsimpson-cc**
[#150141038]

### CODE REVIEW

**Comment by jsimpson-cc** [comment]
@emcelroy Please review when you have a chance. Thanks.

**Comment by emcelroy** [comment]
@jsimpson-cc, @scytacki: That's good thanks, but I'd prefer a tiny change to make it 100% clear we've emailed the person directly. Does this sound good/make sense to you?

"We've sent you an email containing your username and a link for changing your password if you've forgotten it."

**Comment by jsimpson-cc** [comment]
Yes that sounds good. I will update this.

**Comment by scytacki** [comment]
The only think not passing on this is are the pesky Jasmine tests. So I think it is fine to merge.

**Pull request merged**
