### PR TITLE
Unify around HTTParty

### LINKED ISSUE #624: Remove HttpClient in favor of HttParty
Unify code around a single gem.

### PR DESCRIPTION
**Pull request by tjchambers**
Remove HTTPClient gem. Fixes #624.

### CODE REVIEW

**Comment by scytacki** [comment]
I restarted the travis build to see that fixes the problem. I checked and the working build and this previously failing build were both using the same version of google-chrome-stable (69.0.3497.100-1).

So it is could be:
- some weird interaction with httpclient,
- some change to the travis build environment, which seems unlikely because later builds worked on other branches.
- some random issue, this seems most likely to me, but also weird because it failed on all the jobs not just one, and I thought the jobs would be isolated from each other, they do share a cache though, so perhaps the cache contains some broken config for chromedriver

**Comment by scytacki** [comment]
The rebuild fixed the chromedriver issue and found what looks like a legitimate issue with the switch to httparty: https://travis-ci.org/concord-consortium/rigse/jobs/429803379#L2856-L2870

**Comment by tjchambers** [comment]
@scytacki thanks - this is green again. Ready for re-review.

**Comment by scytacki** [comment]
There might be a problem that some image questions in the database don't have a valid protocol. I'll check...

**Comment by tjchambers** [comment]
I could change the code to prepend `http:` if the prefix is missing. I hesitated to do that, but could. I always prefer a prefix to be declared or https.

**Comment by scytacki** [comment]
I looked into this, and it seems fine. We do have some image_url that might get passed in that don't start with http*, but they are all invalid URLs anyhow. So it is fine for them to cause exceptions.

**Pull request merged**
