### PR TITLE
Updated account confirmation email message and added text only version.

### PR DESCRIPTION
**Pull request by emcelroy**

### CODE REVIEW

**Comment by knowuh** [comment]
Looks good to me.

**Comment by scytacki** [comment]
There are 4 failing test related to registration:
https://travis-ci.org/concord-consortium/rigse/jobs/188679741#L1280-L1281
https://travis-ci.org/concord-consortium/rigse/jobs/188679742#L1277-L1278

I think they are failing because the test is trying to open the email and click the first link in the email using this helper method:
`click_first_link_in_email`

That comes from the email-spec gem. We are using an old version. Perhaps there is a upgrade or another method we should use instead.

**Comment by scytacki** [comment]
Yup. I just looked at the gem and it is just finding the first URL in the email and trying to visit. In the new emails format this is a URL to the banner.  I think the correct fix is to replace `click_first_link_in_email` with `visit_in_email('/users/').  I'm not sure the '/users/' part is correct, but I'm guessing it will work.

@emcelroy I also noticed that you are hardcoding the URL to the banner asset. 
https://learn.concord.org/assets/banners/learn-aa43865ea93b51f353fe57a1aa05d624.png
You should use a helper method to get the correct banner for the current portal.

**Comment by scytacki** [comment]
I was confused by the test is now passing. The `click_first_link_in_email` should still have been trying to load the image URL.  I think the reason the test is passing now is because `config/environments/test.rb` was not updated.  So in the test environment the image url is relative so the url matcher used by `click_first_link_in_email` will not find find this link.

I'm going add some changes to address this, just to keep things more clean. If they don't work then I think we can just go with what you have.

**Comment by scytacki** [comment]
Now lets see after this change if the tests still pass...

**Comment by scytacki** [comment]
👍

**Pull request merged**
