### PR TITLE
176237537 - Small change in NGSA portal footer

### PR DESCRIPTION
**Pull request by emcelroy**
PT Story: https://www.pivotaltracker.com/story/show/176237537

[#176237537]

* Update funder links in footer
* Remove unnecessary white space after links

### CODE REVIEW

**Comment by scytacki** [comment]
@knowuh Since you are looking at NSGA you should probably be aware of this change.

**Comment by knowuh** [comment]
I had to review what `= succeed do` does in HAML. 😀

https://www.rubydoc.info/github/haml/haml/Haml%2FHelpers:succeed
https://stackoverflow.com/questions/16291234/why-use-succeed-do-in-haml

**Comment by emcelroy** [comment]
Yeah, I wish I didn't have to use `succeed do`, but it seemed like the best way to get rid of unwanted white space after the `link_to` items.

@knowuh @scytacki Is there any chance this could be pushed to production soon? Dan was eager to get this change made as soon as possible, but it got delayed a bit because I was on vacation.

**Comment by scytacki** [comment]
This was added directly to the `v1.37.x` branch

**Pull request closed without merging**
