### PR TITLE
If a user logs in from a project landing page, redirect back to that page upon login

### PR DESCRIPTION
**Pull request by pjanik**
[#107521084]

### CODE REVIEW

**Comment by scytacki** [comment]
Putting redirect locations like this in the session has caused us problems in the past.  Can you pass this redirect_path in the post params to the login action instead?

**Comment by pjanik** [comment]
@scytacki, I wish I could. I was thinking about it, but Devise docs mention only session-based approach. They even provide their own helper (which basically works the same way): 
- code: https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/store_location.rb
- docs (outdated): https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

Here is the `sign_in` method:
https://github.com/plataformatec/devise/blob/7df57d5081f9884849ca15e4fde179ef164a575f/app/controllers/devise/sessions_controller.rb#L15-L22
It doesn't seem to support any params, only the `resource` object is provided to `after_sign_in_path_for` method, which is an `User` instance in our case.

**Comment by scytacki** [comment]
Since the `after_sign_in_path_for` can access the `session` and current_visitor (even though they are not passed in). I think it is likely it could also access the `params`.  And if not the params, it might be able to access the `request` object which would give access to the params.

**Comment by pjanik** [comment]
@scytacki, thanks! You're obviously right, I somehow assumed that `after_sign_in_path_for` is called later / in an async way and we don't have access to the initial env, request and parameters. Quite strange taking into account that I was looking at the `sing_in` implementation. :flushed: 
I'm closing this pull request and opening a new one: https://github.com/concord-consortium/rigse/pull/169

**Pull request closed without merging**
