### PR TITLE
Made log manager url configurable [#176704163]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Review by scytacki — CHANGES_REQUESTED** [review]
Instead of adding this to app_environment_variables.sample.rb it should be added to `docker-compose.yml`.

**Review by scytacki — APPROVED** [review]
looks good to me

**Review by scytacki — CHANGES_REQUESTED** [review]
Ok this is breaking one of the tests.

**Comment by dougmartin** [comment]
@scytacki the tests should be fixed now.

**Review by scytacki — APPROVED** [review]
Looks good.

**Pull request merged**
