### PR TITLE
backend jobs are failing in dev which is impacting student reports

### PR DESCRIPTION
**Pull request by sri-tscube**

### CODE REVIEW

**Comment by knowuh** [comment]
Hi @sri-tscube 

This issue was also fixed on the rails6 branch in two recent commits:

- https://github.com/concord-consortium/rigse/commit/ea59c95a326d41986f64d240f8b4b389e8c974e2
- https://github.com/concord-consortium/rigse/commit/30b302d44981fc937e08a196d3c0b706d5b8d21a

You could try cherry-picking those into another branch, but because the Gemfile was touched, there may be too many changes to apply cleanly.

I worry that if we merge this PR into master, we might have trouble merging the rails6 PR which should be landing in less than one week.

cc @scytacki @dougmartin

**Comment by sri-tscube** [comment]
> Hi @sri-tscube
> 
> This issue was also fixed on the rails6 branch in two recent commits:
> 
> * [ea59c95](https://github.com/concord-consortium/rigse/commit/ea59c95a326d41986f64d240f8b4b389e8c974e2)
> * [30b302d](https://github.com/concord-consortium/rigse/commit/30b302d44981fc937e08a196d3c0b706d5b8d21a)
> 
> You could try cherry-picking those into another branch, but because the Gemfile was touched, there may be too many changes to apply cleanly.
> 
> I worry that if we merge this PR into master, we might have trouble merging the rails6 PR which should be landing in less than one week.
> 
> cc @scytacki @dougmartin

I can wait till we merge Rails6 changes, Noah. 
We can reject this pull request.
I can make local changes in automation to verify the scripts.
@scytacki, What do you think?

**Comment by scytacki** [comment]
I'm not convinced the release will go out this week, so we might be stuck in this state for another week or two. But I think at this point most major changes are going to happen in the rails6 branch. So it seems OK to stick with local changes for now.

But if the release drags on for another week or two, then it might be worth bring it in, and resolving the merge conflicts. I think once the merge conflict is address, git will be able to handle future merges automatically (unless we change this part of the code again).

So I guess lets leave this PR open a bit longer.

**Comment by sri-tscube** [comment]
> @sri-tscube can you confirm that rails6 (now merged into master) fixes this problem?

I will check it, @scytacki.

**Comment by sri-tscube** [comment]
> @sri-tscube can you confirm that rails6 (now merged into master) fixes this problem?

It's working now, @scytacki

**Pull request closed without merging**
