### PR TITLE
Fix [#98674838] (iframe edit bug)

### PR DESCRIPTION
**Pull request by knowuh**
moved PeerAccess module into services, added '#ssl_if_we_are' method & tests.

iframe edit bug → https://www.pivotaltracker.com/story/show/98674838

### CODE REVIEW

**Comment by knowuh** [comment]
This pull request is mostly a test for a trivial method.  :)  But I had fun.

**Comment by scytacki** [comment]
:+1:

**Comment by knowuh** [comment]
One problem: somehow this caused failing tests in travis.  I just started trying to hunt it down.

**Comment by knowuh** [comment]
The failed tests were these:

       1) Portal::TeacherClazz preserving leagacy one to many mapping for teachers <= clazzes clazz.teacher reader should return the first teacher if there is one
       Failure/Error: clazz.teacher.should == teacher

      2) User disallows illegitimate logins: 'plus+'
           Failure/Error: lambda do
         count should not have changed, but did change from 3 to 4
         # ./spec/models/user_spec.rb:86:in `block (4 levels) in <top (required)>'


Are these known to be volatile?

**Comment by scytacki** [comment]
#1 is known to volatile. #2 just started showing up. #1 has been there for
a few weeks.

#1 seems to be caused by the ordering of elements in the database. My guess
is that our current approach is not good enough when two teachers are added
so close together in time.

#2 might be the same thing, however it started showing up just after I
merged the large Zeus commit yesterday. So it might be a real failure. They
did change the User code.

On Fri, Jul 10, 2015 at 9:38 AM, Noah Paessel <notifications@github.com>
wrote:

> The failed tests were these:
>
>    1) Portal::TeacherClazz preserving leagacy one to many mapping for teachers <= clazzes clazz.teacher reader should return the first teacher if there is one
>    Failure/Error: clazz.teacher.should == teacher
>
>   2) User disallows illegitimate logins: 'plus+'
>        Failure/Error: lambda do
>      count should not have changed, but did change from 3 to 4
>      # ./spec/models/user_spec.rb:86:in `block (4 levels) in <top (required)>'
>
> Are these known to be volatile?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/concord-consortium/rigse/pull/99#issuecomment-120413852>
> .
>



-- 
Scott Cytacki
The Concord Consortium
http://concord.org

**Pull request merged**
