### PR TITLE
Upgrade test suite tooling & syntax

### PR DESCRIPTION
**Pull request by benjaminwood**
This PR accomplishes a few things:

1. Upgrades `rspec` from v2.99 to latest v3.8.0
2. Converts all `rspec` v2 `should` style syntax to `expect` (in rspec suite & cucumber step definitions)
3. Upgrades `capybara` from v1.1.2 to v2.18.0
4. Upgrades `webmock` from v1.11.0 to v3.4.2
5. Removes `fakeweb` converting remaining usage to webmock.

### CODE REVIEW

**Comment by benjaminwood** [comment]
:tada: :tada: :tada: :tada: 

A green build! Ready for review @scytacki.

**Comment by scytacki** [comment]
Looks great! Nice Work.

I'll try to fix up the failing feature.

**Comment by scytacki** [comment]
Here is a commit fixing the test: https://github.com/concord-consortium/rigse/commit/34ed039ece9344d1b3f3f223386c1f944111e965 I'm waiting to see if the branch tests green: https://travis-ci.org/concord-consortium/rigse/builds/414937270?utm_source=github_status&utm_medium=notification

**Comment by benjaminwood** [comment]
Awesome!

**Pull request merged**
